### PR TITLE
Creating a Cargo workspace with git submodules for our own crates

### PR DESCRIPTION
**Pull request by nishaq503**
This makes for a unified development environment for all our packages and Cargo can ensure that they all work together through the use of a cargo workspace.

This also separates the python and rust code bases for CLAM.

### CODE REVIEW

**Comment by nishaq503** [comment]
Currently, github actions are failing because Cargo fails to load a path dependency to a git submodule of the `distances` crate. It works locally for me and I've been spinning my wheels trying to work through this. Perhaps @thoward27 would have some insight?

**Comment by nishaq503** [comment]
> Currently, github actions are failing because Cargo fails to load a path dependency to a git submodule of the `distances` crate. It works locally for me and I've been spinning my wheels trying to work through this. Perhaps @thoward27 would have some insight?

Well I think I figured out the issue here.

**Comment by thoward27** [comment]
> > Currently, github actions are failing because Cargo fails to load a path dependency to a git submodule of the `distances` crate. It works locally for me and I've been spinning my wheels trying to work through this. Perhaps @thoward27 would have some insight?
> 
> Well I think I figured out the issue here.

What was it in the end?

**Comment by nishaq503** [comment]
> > > Currently, github actions are failing because Cargo fails to load a path dependency to a git submodule of the `distances` crate. It works locally for me and I've been spinning my wheels trying to work through this. Perhaps @thoward27 would have some insight?
> > 
> > 
> > Well I think I figured out the issue here.
> 
> What was it in the end?

I had to initialize the git submodules in the github actions.

**Pull request closed without merging**
